import type { EpisodeRecord } from "@/lib/types/episodes";

export const DEMO_USER_ID = "demo-user";

export const DEMO_EPISODES: EpisodeRecord[] = [
  {
    id: "demo-1",
    user_id: DEMO_USER_ID,
    pain_type_labels: ["Trigeminal Neuralgia"],
    pain_pattern: "episodic_pulsing",
    pulse_duration_seconds: 2,
    face_areas: ["v2"],
    face_points: [
      { x: 280, y: 430, division: "v2", location: "right_cheek", label: "Right cheek" },
    ],
    severity: 8,
    duration_seconds: 610,
    onset_at: "2026-02-14T15:30:00.000Z",
    trigger_labels: ["Cold air", "Touching face"],
    medication_labels: ["Carbamazepine"],
    notes: "Started after going outside in the wind.",
    treatment_history_changed: false,
    treatment_change_date: null,
    treatment_history_snapshot: null,
    created_at: "2026-02-14T15:40:00.000Z",
  },
  {
    id: "demo-2",
    user_id: DEMO_USER_ID,
    pain_type_labels: ["Trigeminal Neuralgia"],
    pain_pattern: "episodic_pulsing",
    pulse_duration_seconds: 1,
    face_areas: ["v3"],
    face_points: [
      { x: 280, y: 520, division: "v3", location: "right_jaw", label: "Right jaw" },
    ],
    severity: 6,
    duration_seconds: 915,
    onset_at: "2026-03-03T08:10:00.000Z",
    trigger_labels: ["Brushing teeth", "Flossing"],
    medication_labels: ["Oxcarbazepine", "Ibuprofen"],
    notes: "Short but sharp pain while brushing teeth.",
    treatment_history_changed: false,
    treatment_change_date: null,
    treatment_history_snapshot: null,
    created_at: "2026-03-03T08:20:00.000Z",
  },
  {
    id: "demo-3",
    user_id: DEMO_USER_ID,
    pain_type_labels: ["Occipital Neuralgia"],
    pain_pattern: "continuous",
    pulse_duration_seconds: null,
    face_areas: ["v1"],
    face_points: [
      { x: 500, y: 140, division: "v1", location: "forehead", label: "Forehead" },
    ],
    severity: 7,
    duration_seconds: 1830,
    onset_at: "2026-03-21T19:45:00.000Z",
    trigger_labels: ["Stress"],
    medication_labels: ["Gabapentin"],
    notes: "Felt more intense after a long day.",
    treatment_history_changed: false,
    treatment_change_date: null,
    treatment_history_snapshot: null,
    created_at: "2026-03-21T19:50:00.000Z",
  },
  {
    id: "demo-4",
    user_id: DEMO_USER_ID,
    pain_type_labels: ["Geniculate Neuralgia"],
    pain_pattern: "episodic_pulsing",
    pulse_duration_seconds: 3,
    face_areas: ["v2"],
    face_points: [
      { x: 720, y: 430, division: "v2", location: "left_cheek", label: "Left cheek" },
    ],
    severity: 9,
    duration_seconds: 1220,
    onset_at: "2026-04-05T12:05:00.000Z",
    trigger_labels: ["Talking", "Chewing"],
    medication_labels: ["Baclofen", "Acetaminophen"],
    notes: "Pain spiked during a longer conversation.",
    treatment_history_changed: true,
    treatment_change_date: "2026-03-15",
    treatment_history_snapshot: {
      prior_treatments: [{ treatment_type: "mvd", other_label: null }],
      other_therapies: [{ therapy_type: "acupuncture", other_label: null }],
      added_prior_treatments: [{ treatment_type: "mvd", other_label: null }],
      added_other_therapies: [{ therapy_type: "acupuncture", other_label: null }],
    },
    created_at: "2026-04-05T12:20:00.000Z",
  },
  {
    id: "demo-5",
    user_id: DEMO_USER_ID,
    pain_type_labels: ["Anesthesia Dolorosa"],
    pain_pattern: "continuous",
    pulse_duration_seconds: null,
    face_areas: ["v1", "v2", "v3"],
    face_points: [
      { x: 500, y: 140, division: "v1", location: "forehead", label: "Forehead" },
      { x: 280, y: 430, division: "v2", location: "right_cheek", label: "Right cheek" },
      { x: 500, y: 540, division: "v3", location: "chin", label: "Chin" },
    ],
    severity: 5,
    duration_seconds: 2705,
    onset_at: "2026-04-18T06:50:00.000Z",
    trigger_labels: ["Spontaneous / no clear trigger"],
    medication_labels: ["No medication"],
    notes: "Low-level background pain most of the day.",
    treatment_history_changed: false,
    treatment_change_date: null,
    treatment_history_snapshot: null,
    created_at: "2026-04-18T07:00:00.000Z",
  },
];
