import type { EpisodeRecord } from "@/lib/types/episodes";

export const DEMO_USER_ID = "demo-user";

export const DEMO_EPISODES: EpisodeRecord[] = [
  {
    id: "demo-1",
    user_id: DEMO_USER_ID,
    pain_type: "trigeminal_neuralgia",
    face_areas: ["left_cheek"],
    severity: 8,
    duration_seconds: 610,
    onset_at: "2026-02-14T15:30:00.000Z",
    trigger_labels: ["Cold air", "Touching face"],
    medication_labels: ["Carbamazepine"],
    notes: "Started after going outside in the wind.",
    created_at: "2026-02-14T15:40:00.000Z",
  },
  {
    id: "demo-2",
    user_id: DEMO_USER_ID,
    pain_type: "trigeminal_neuralgia",
    face_areas: ["jaw"],
    severity: 6,
    duration_seconds: 915,
    onset_at: "2026-03-03T08:10:00.000Z",
    trigger_labels: ["Brushing teeth", "Flossing"],
    medication_labels: ["Oxcarbazepine", "Ibuprofen"],
    notes: "Short but sharp pain while brushing teeth.",
    created_at: "2026-03-03T08:20:00.000Z",
  },
  {
    id: "demo-3",
    user_id: DEMO_USER_ID,
    pain_type: "occipital_neuralgia",
    face_areas: ["eye_forehead"],
    severity: 7,
    duration_seconds: 1830,
    onset_at: "2026-03-21T19:45:00.000Z",
    trigger_labels: ["Stress"],
    medication_labels: ["Gabapentin"],
    notes: "Felt more intense after a long day.",
    created_at: "2026-03-21T19:50:00.000Z",
  },
  {
    id: "demo-4",
    user_id: DEMO_USER_ID,
    pain_type: "geniculate_neuralgia",
    face_areas: ["right_cheek"],
    severity: 9,
    duration_seconds: 1220,
    onset_at: "2026-04-05T12:05:00.000Z",
    trigger_labels: ["Talking", "Chewing"],
    medication_labels: ["Baclofen", "Acetaminophen"],
    notes: "Pain spiked during a longer conversation.",
    created_at: "2026-04-05T12:20:00.000Z",
  },
  {
    id: "demo-5",
    user_id: DEMO_USER_ID,
    pain_type: "anesthesia_dolorosa",
    face_areas: ["left_cheek", "jaw", "eye_forehead"],
    severity: 5,
    duration_seconds: 2705,
    onset_at: "2026-04-18T06:50:00.000Z",
    trigger_labels: ["Spontaneous / no clear trigger"],
    medication_labels: ["No medication"],
    notes: "No obvious trigger that morning.",
    created_at: "2026-04-18T07:35:00.000Z",
  },
];
